# Generated by Django 2.0 on 2019-11-15 14:54

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='upload',
            field=models.FileField(blank=True, upload_to=articles.models.user_directory_path),
        ),
    ]
