# Generated by Django 2.2.7 on 2019-12-04 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='article', to='articles.Article'),
        ),
    ]
